### PR TITLE
Add test metadata versioning

### PR DESCRIPTION
**Pull request by flacatus**
Test metadata task is versioning.

### CODE REVIEW

**Review by Roming22 — APPROVED** [review]

**Comment by flacatus** [comment]
should fail until we merge: https://github.com/konflux-ci/konflux-qe-definitions/pull/21

**Comment by Roming22** [comment]
@flacatus CI still failing, task can't be found: https://console.redhat.com/preview/application-pipeline/workspaces/rhtap-shared/applications/rhtap-cli/pipelineruns/rhtap-cli-npxbd-wnqvj

**Pull request merged**
