### PR TITLE
RHTAPINST-133: Local and Embedded ChartFS

### PR DESCRIPTION
**Pull request by otaviof**
Supports local and embedded files via `ChartFS`, the component looks for the data in the local filesystem first, and if not found, it looks for the data in the embedded filesystem.

Removing the flag `--embedded`, given both local and embedded FS are working in combination.

### CODE REVIEW

**Comment by otaviof** [comment]
/hold cancel

I forgot to remove the `--embedded` flag, now it's ready.

**Review by Roming22 — APPROVED** [review]
/lgtm

**Review by Roming22 — APPROVED** [review]
/lgtm

**Comment by rhopp** [comment]
One run passed: https://console.redhat.com/application-pipeline/workspaces/rhtap-shared-team/applications/rhtap-cli/pipelineruns/e2e-4.17-b7c77
One failed: https://console.redhat.com/application-pipeline/workspaces/rhtap-shared-team/applications/rhtap-cli/pipelineruns/e2e-4.16-8kgsz
on what seems to be error while running (in tests)
```
argocd app sync xpyxt0gbi-java-quarkus-stage --insecure
```
```
msg="rpc error: code = FailedPrecondition desc = another operation is already in progress"
```
I'll keep an eye for this failure, but wouldn't hold this PR because of it. Feel free to merge from my (e2e-tests) POV

**Pull request merged**
