### PR TITLE
a minior update for install.sh

### PR DESCRIPTION
**Pull request by xinredhat**

### CODE REVIEW

**Review by jkopriva — APPROVED** [review]

**Comment by xinredhat** [comment]
erros
```
### [1/20] Waiting for 5 seconds before retrying...
# Checking if statefulset with selector 'v1.min.io/tenant=tpa' exists...
# Resource of type 'statefulset' with selector 'v1.min.io/tenant=tpa' exists in namespace 'rhtap-tpa'!
# Checking if statefulset with selector 'v1.min.io/tenant=tpa' is ready...
Waiting for 1 pods to be ready...
error: timed out waiting for the condition
```

**Review by Roming22 — APPROVED** [review]
/lgtm

**Review by Roming22 — APPROVED** [review]
/lgtm

**Review by Roming22 — APPROVED** [review]
/lgtm

**Pull request merged**
