### PR TITLE
RHTAPINST-166: extract login logic from rhtap-install task (version 2)

### PR DESCRIPTION
**Pull request by rhopp**

### CODE REVIEW

**Comment by rhopp** [comment]
This PR should supersede https://github.com/redhat-appstudio/rhtap-cli/pull/288 after discussion in slack

**Comment by rhopp** [comment]
Here's the successful run with the temp commit ensuring task from this PR is being used: https://console.redhat.com/application-pipeline/workspaces/rhtap-shared-team/applications/rhtap-cli/commit/a9bca87109eb28fc195f254134615c65d94ab793
Now I've removed that commit and force-pushed it. The CI is now expected to fail, but should be safe to merge.

**Review by xinredhat — APPROVED** [review]

**Review by Roming22 — APPROVED** [review]

**Pull request merged**
