### PR TITLE
feat: use hermetic builds for rhtap-cli

### PR DESCRIPTION
**Pull request by flacatus**

### CODE REVIEW

**Review by Roming22 — APPROVED** [review]

**Comment by Roming22** [comment]
@flacatus can you confirm this PR is ready to be merged on your end?

**Comment by flacatus** [comment]
@Roming22 should be ready

**Review by Roming22 — APPROVED** [review]
/lgtm

**Comment by Roming22** [comment]
@flacatus Build is failing as go can't access the internet to download the kubectl sources. Maybe that can be done in the prefetch task?

**Pull request closed without merging**
