### PR TITLE
fixed the issue that docker.io rate limiting

### PR DESCRIPTION
**Pull request by xinredhat**

### CODE REVIEW

**Comment by Roming22** [comment]
This PR can be forced merged as long as the `rhtap-install` step is successful.

**Comment by xinredhat** [comment]
> This PR can be forced merged as long as the `rhtap-install` step is successful.

@Roming22 this [result](https://console.redhat.com/application-pipeline/workspaces/rhtap-shared-team/applications/rhtap-cli/pipelineruns/rhtap-cli-sd9ql-4l7v7) already verified that  the rhtap-install step is successful.

**Comment by Roming22** [comment]
@xinredhat All right, it passed again with https://console.redhat.com/application-pipeline/workspaces/rhtap-shared-team/applications/rhtap-cli/pipelineruns/rhtap-cli-9m44t-n5vb4, so I'm force merging that change. We can fix the next failure in another PR.

**Comment by xinredhat** [comment]
the rhtap-install step is successful again , see the [link](https://github.com/redhat-appstudio/rhtap-cli/pull/246/checks?check_run_id=30861155118) . I changed the `rhtap-install` step back to  the `main` branch. This PR can be forced merged now.

**Pull request merged**
