### PR TITLE
RHTAPINST-145: Windows Executable

### PR DESCRIPTION
**Pull request by otaviof**
Plus documentation to describe more about `goreleaser` usage.

### CODE REVIEW

**Comment by Roming22** [comment]
@otaviof Please add some text about how deployment is not compatible with Windows.

**Comment by otaviof** [comment]
> @otaviof Please add some text about how deployment is not compatible with Windows.

Please consider latest changes.

**Review by Roming22 — APPROVED** [review]
/lgtm

**Pull request merged**
